[build]
builder = "NIXPACKS"
buildCommand = "npm run build:cloud"

[deploy]
startCommand = "npm run start:cloud"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
