const PERMISSIONS = {
  // Dashboard
  DASHBOARD_VIEW: 'dashboard.view',
  DASHBOARD_ADMIN: 'dashboard.admin',

  // Users
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',

  // Customers
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_CREATE: 'customers.create',
  CUSTOMERS_UPDATE: 'customers.update',
  CUSTOMERS_DELETE: 'customers.delete',

  // Animals
  ANIMALS_VIEW: 'animals.view',
  ANIMALS_CREATE: 'animals.create',
  ANIMALS_UPDATE: 'animals.update',
  ANIMALS_DELETE: 'animals.delete',

  // Samples
  SAMPLES_VIEW: 'samples.view',
  SAMPLES_CREATE: 'samples.create',
  SAMPLES_UPDATE: 'samples.update',
  SAMPLES_DELETE: 'samples.delete',
  SAMPLES_ASSIGN: 'samples.assign',

  // Tests
  TESTS_VIEW: 'tests.view',
  TESTS_MANAGE: 'tests.manage',
  PRICE_LIST_VIEW: 'price_list.view',

  // Results
  RESULTS_VIEW: 'results.view',
  RESULTS_ENTER: 'results.enter',
  RESULTS_VALIDATE: 'results.validate',
  RESULTS_UPLOAD_IMAGES: 'results.upload_images',

  // Reports
  REPORTS_VIEW: 'reports.view',
  REPORTS_GENERATE: 'reports.generate',

  // Billing
  BILLING_VIEW: 'billing.view',
  BILLING_CREATE: 'billing.create',
  BILLING_PAYMENT: 'billing.payment',
  BILLING_REFUND: 'billing.refund',
  BILLING_CANCEL: 'billing.cancel',
  BILLING_DAY_CLOSE: 'billing.day_close',
  BILLING_DAY_REOPEN: 'billing.day_reopen',

  // Inventory
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_MANAGE: 'inventory.manage',

  // Quality
  QUALITY_VIEW: 'quality.view',
  QUALITY_MANAGE: 'quality.manage',

  // Settings
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_MANAGE: 'settings.manage',

  // Audit
  AUDIT_VIEW: 'audit.view',

  // Devices
  DEVICES_VIEW: 'devices.view',
  DEVICES_MANAGE: 'devices.manage',
};

const ROLE_PERMISSIONS = {
  admin: Object.values(PERMISSIONS),
  manager: [
    PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DASHBOARD_ADMIN,
    PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_UPDATE,
    PERMISSIONS.ANIMALS_VIEW, PERMISSIONS.ANIMALS_CREATE, PERMISSIONS.ANIMALS_UPDATE,
    PERMISSIONS.SAMPLES_VIEW, PERMISSIONS.SAMPLES_CREATE, PERMISSIONS.SAMPLES_UPDATE, PERMISSIONS.SAMPLES_ASSIGN,
    PERMISSIONS.TESTS_VIEW, PERMISSIONS.TESTS_MANAGE,
    PERMISSIONS.PRICE_LIST_VIEW,
    PERMISSIONS.RESULTS_VIEW, PERMISSIONS.RESULTS_VALIDATE,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.BILLING_VIEW, PERMISSIONS.BILLING_CREATE, PERMISSIONS.BILLING_PAYMENT,
    PERMISSIONS.BILLING_REFUND, PERMISSIONS.BILLING_CANCEL, PERMISSIONS.BILLING_DAY_CLOSE, PERMISSIONS.BILLING_DAY_REOPEN,
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.QUALITY_VIEW, PERMISSIONS.QUALITY_MANAGE,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.DEVICES_VIEW, PERMISSIONS.DEVICES_MANAGE,
  ],
  reception: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_UPDATE,
    PERMISSIONS.ANIMALS_VIEW, PERMISSIONS.ANIMALS_CREATE, PERMISSIONS.ANIMALS_UPDATE,
    PERMISSIONS.SAMPLES_VIEW, PERMISSIONS.SAMPLES_CREATE, PERMISSIONS.SAMPLES_UPDATE,
    PERMISSIONS.TESTS_VIEW, PERMISSIONS.PRICE_LIST_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.BILLING_VIEW, PERMISSIONS.BILLING_CREATE,
  ],
  lab_technician: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SAMPLES_VIEW, PERMISSIONS.SAMPLES_UPDATE, PERMISSIONS.SAMPLES_ASSIGN,
    PERMISSIONS.TESTS_VIEW,
    PERMISSIONS.RESULTS_VIEW, PERMISSIONS.RESULTS_ENTER, PERMISSIONS.RESULTS_UPLOAD_IMAGES,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.QUALITY_VIEW, PERMISSIONS.QUALITY_MANAGE,
  ],
  lab_specialist: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SAMPLES_VIEW,
    PERMISSIONS.TESTS_VIEW,
    PERMISSIONS.RESULTS_VIEW, PERMISSIONS.RESULTS_VALIDATE,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.QUALITY_VIEW,
  ],
  veterinarian: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.ANIMALS_VIEW,
    PERMISSIONS.SAMPLES_VIEW,
    PERMISSIONS.TESTS_VIEW,
    PERMISSIONS.RESULTS_VIEW, PERMISSIONS.RESULTS_VALIDATE,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_GENERATE,
  ],
  accountant: [
    PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DASHBOARD_ADMIN,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.BILLING_VIEW, PERMISSIONS.BILLING_CREATE, PERMISSIONS.BILLING_PAYMENT, PERMISSIONS.BILLING_REFUND,
    PERMISSIONS.BILLING_DAY_CLOSE,
    PERMISSIONS.PRICE_LIST_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
};

module.exports = { PERMISSIONS, ROLE_PERMISSIONS };
